services:
  app:
    build: .
    image: study-bingo:1.0
    container_name: study-bingo-app
    stdin_open: true
    tty: true
    command: ["python", "src/game.py"]

    volumes:
      - bingo_data:/app/data:ro   # volumen Docker, no depende del host

volumes:
  bingo_data: