version: "3.8"

services:
  app:
    build: .
    image: study-bingo:1.0
    container_name: study-bingo-app
    stdin_open: true   # like -i in docker run (allows input)
    tty: true          # like -t in docker run (allocates a TTY)
    command: ["python", "src/game.py"]
    volumes:
      - ./data:/app/data

